-- Pesito: número simple y secuencial por negocio (Negocio N° 1, 2, 3...),
-- para usar en soporte técnico en vez del UUID completo de organizations.id
-- (correcto pero imposible de dictar/tipear a mano).
-- Corre sobre una base que ya tiene 0001..0031 aplicadas.

alter table organizations
  add column if not exists org_number bigint generated by default as identity unique;
